services:
  main_mq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - main_rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${MAIN_MQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${MAIN_MQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q status"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - microservice-network

  wrappers_mq:
    image: rabbitmq:3-management
    ports:
      - "5674:5672"
      - "15674:15672"
    volumes:
      - wrappers_rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${WRAPPERS_MQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${WRAPPERS_MQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q status"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - microservice-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - microservice-network

  ingestor:
    build:
      context: ./Ingestor
      dockerfile: Dockerfile
    command: ["python", "src/main.py"]
    volumes:
      - ./Ingestor:/app
    environment:
      - PYTHONUNBUFFERED=1
      - WRAPPERS_MQ_DEFAULT_USER=${WRAPPERS_MQ_DEFAULT_USER}
      - WRAPPERS_MQ_DEFAULT_PASS=${WRAPPERS_MQ_DEFAULT_PASS}
      - WRAPPERS_MQ_HOST=${WRAPPERS_MQ_HOST}
      - WRAPPERS_MQ_PORT=${WRAPPERS_MQ_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      wrappers_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - microservice-network

  propagator:
    build:
      context: ./Propagator
      dockerfile: Dockerfile
    command: ["python", "src/main.py"]
    volumes:
      - ./Propagator:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MAIN_MQ_DEFAULT_USER=${MAIN_MQ_DEFAULT_USER}
      - MAIN_MQ_DEFAULT_PASS=${MAIN_MQ_DEFAULT_PASS}
      - MAIN_MQ_HOST=${MAIN_MQ_HOST}
      - MAIN_MQ_PORT=${MAIN_MQ_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      main_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - microservice-network

  wrappers:
    build:
      context: ./Wrappers
      dockerfile: Dockerfile
    command: ["python", "src/main.py"]
    volumes:
      - ./Wrappers:/app
    environment:
      - PYTHONUNBUFFERED=1
      - WRAPPERS_MQ_DEFAULT_USER=${WRAPPERS_MQ_DEFAULT_USER}
      - WRAPPERS_MQ_DEFAULT_PASS=${WRAPPERS_MQ_DEFAULT_PASS}
      - WRAPPERS_MQ_HOST=${WRAPPERS_MQ_HOST}
      - WRAPPERS_MQ_PORT=${WRAPPERS_MQ_PORT}
    depends_on:
      wrappers_mq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - microservice-network

volumes:
  main_rabbitmq_data:
    driver: local
  wrappers_rabbitmq_data:
    driver: local
  redis_data:
    driver: local

networks:
  microservice-network:
    external: true